name: kettle_timeup
description: A new Flutter application about time schedule.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.3+9

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  dynamic_color: ^1.7.0
  numberpicker: ^2.0.0
  shared_preferences: ^2.2.2
  # awesome_notifications_core: ^0.10.0
  # awesome_notifications: ^0.8.1
  # awesome_notifications_fcm: 
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^18.0.1
  flutter_background_service: ^5.0.10
  workmanager: ^0.5.2
  device_info_plus: ^11.1.1
  audioplayers: ^6.1.0
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/timer_finished.wav

flutter_launcher_icons:
  android: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "@android:color/system_accent1_100"
  adaptive_icon_foreground: "assets/images/icon.png"
  min_sdk_android: 26